app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    author = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitches', backref='author', lazy='dynamic')
    comments = db.relationship('Comments', backref='author', lazy='dynamic')

#to link tables what you add after backref matters
    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'Author: {self.author}'

class Pitches(db.Model):
    __tablename__= 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,cate):
        pitch = Pitches.query.filter_by(category=cate).all()
        return pitch

    def __repr__(self):
        return f"Pitches {self.pitch}','{self.date}')"

class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comments = Comments.query.filter_by(pitches_id=id).all()
        return comments

    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import InputRequired

class PitchForm(FlaskForm):
    title = StringField("Pitch Title")
    category = SelectField(u"Pitch Category",choices=[("interview", "interview"),("funny","funny"),("promotion","promotion"),("product","product"),("random","random")])
    pitch = TextAreaField('Pitch')
    submit = SubmitField("Submit")

# add comment

class CommentForm(FlaskForm):
    
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

# update profile

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE




login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):
    

    app = Flask(__name__)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
     # configure UploadSet
    configure_uploads(app,photos)
    

    # Initializing flask extensions
    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

      # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # secret
    app.secret_key='SECRET_KEY'



    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask_login import login_required,current_user
from ..models import Pitches, User, Comments
from . import main
from .. import db,photos
from .forms import PitchForm,CommentForm, UpdateProfile

# blueprint views
from flask import render_template,request,redirect,url_for,abort


# main route
@main.route('/')
def index():
    '''
    my index page
    return
    '''
    message= "Hello"
    title= 'Pitch'
    return render_template('index.html', message=message,title=title)

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        title=form.title.data

        # Updated pitchinstance
        new_pitch = Pitches(title=title,category= category,pitch= pitch,user_id=current_user.id)

        title='New Pitch'

        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    return render_template('pitch.html',pitch_entry= form)

    # main route categories
@main.route('/categories/<cate>')
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, category = category)

    # profile username
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.author))

    return render_template('profile/update.html',form =form)

# updating profile picture 
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

# login to make comment
@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    print(comm)
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

# make new comment
@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user_id=current_user.id, pitches_id=pitches_id)


        new_comment.save_comment()


        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>

   <meta charset="utf-8">
   {% if title %}
   <title>{{ title }}</title>
   {% else %}
   <title>Choose </title>
   {% endif %}
 </head>
 <body>

   {% block content %}

   {% endblock %}

</body>

app/templates/categories.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

{% endblock %}

<br>
<br>
<br>
<br>


<body>
  {% block content %}
  <br>
  <br>
  <div class="container">
    <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
    <br>
    <br>
    <br>
    <div class="card-columns">
      {% for category in category[::-1] %}
  
      <div class="card bg-transparent border-success">
        <div class="card-header bg-transparent border-success">
          {{category.title}}
        </div>
        <div class="card-body text">
          <blockquote class="blockquote mb-0">
            <p>{{category.pitch}}</p><br>
            <footer class="blockquote-footer bg-transparent border-success">{{category.author}}
              <br><cite title="Source Title">Publish date: {{category.date.strftime('%Y-%m-%d')}}</cite>
            </footer>
          </blockquote>
        </div>
        <div class="card-footer bg-transparent border-success">
          <button type="button" class="btn btn-outline-success btn-sm"><a
              href="/new_comment/{{category.id}}">Comment</a></button> <button type="button"
            class="btn btn-outline-success btn-sm"><a href="/comments/{{category.id}}">View comments</a></button>
        </div>

        <p id="UpvoteCount"></p>

        <!-- upvote and downvote -->
        <div class="card-footer bg-transparent border-success">
          <button type="button" id="like" class="btn btn-info btn-sm">

            <a class="text-decoration-none text-light" href="">Upvote <i class="fas fa-thumbs-up"></i></a></button>
          <button type="button" class="btn btn-danger btn-sm"><a class="text-decoration-none text-light" href="">Downvote
              <i class="fas fa-thumbs-down"></i></a>
          </button>
        </div>
      </div>

      {% endfor %}

    </div>
    {% endblock %}
  </body>

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<br>
<br>

<body>
  {% for comm in comment[::-1] %}
  <div class="container">
    <div class="card-groups">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{comm.author}}</h4>
          <p class="card-text">{{comm.comment}}.</p>
        </div>
        <div class="card-footer bg-transparent border-success"><small class="text-muted">Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small></div>
      </div>
    </div>
  </div>

  {% endfor %}

  {% endblock %}
</body>

app/templates/fourowfour.html
{% extends 'base.html'%}

{% block content %}
<br>
<br>
    <h1>WHOOOPS! we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

<!-- styles block -->
{% block styles%} {{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">"
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="static/css/style.css">


<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock %}
{% block content %}

<body>
  <br>
  <div class="container">
  <div class="row align-items-center">
    <!-- interview pitches -->
      <div class="col-md-12">
  <div class="d-flex justify-content-center">
    <div class="card-groups">
      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">INTERVIEW</div>
        <div class="card-body text-info">
          <h5 class="card-title">Interview Pitch</h5>
          <p class="card-text">Change people's mindset and thinking concerning interviews and give them ideas on how to conduct themselves better.</p>
          <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-primary"><a href="/categories/Interview">View Pitch</a></button>
        </div>
      </div>
      </div>

      <!-- random pitches -->
      <div class="col">
      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">RANDOM</div>
        <div class="card-body text-info">
          <h5 class="card-title">Random Pitches</h5>
          <p class="card-text">Take this takeaway to display any random pitch in your mind.</p>
          <button type="button" class="btn btn-outline-secondary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-secondary"><a href="/categories/Random">View Pitch</a></button>
        </div>
      </div>
      </div>
      <!-- funny pitches -->
      <div class="col">
      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">JUST FOR LAUGHS</div>
        <div class="card-body text-info">
          <h5 class="card-title">Funny Pitches</h5>
          <p class="card-text">Post something to funny to crack us</p>
          <button type="button" class="btn btn-outline-secondary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-secondary"><a href="/categories/Funny">View Pitch</a></button>
        </div>
      </div>
      </div>
      <!-- pitches about promotion -->
      <div class="col">
      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">PROMOTION</div>
        <div class="card-body text-info">
          <h5 class="card-title">Promotional Pitches</h5>
          <p class="card-text">Take this opportunity to promote any product you wish</p>
          <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-primary"><a href="/categories/Promotion">View Pitch</a></button>
        </div>
      </div>
      </div>
    </div>
  </div>
  </div>
  </div>

  {% endblock%}
  
</body>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #363436;">
    <a class="navbar-brand" href="/">Welcome to PitchAPP</a>
    
    <div class="collapse navbar-collapse display-6" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li> <br><br><br>
        <li class="nav-item">
          <a class="nav-link" href="/categories/Interviews">Interviews</a>
        </li> <br><br>
        <li class="nav-item">
          <a class="nav-link" href="/categories/Promotion">Promotion</a>
        </li> <br><br>
        <li class="nav-item">
          <a class="nav-link" href="/categories/random">Random</a>
        </li> <br><br>
        <li class="nav-item">
            <a class="nav-link" href="/categories/funny">funny</a>
        </li> <br><br>
        <li class="nav-item">
            <a class="nav-link" href="/categories/product">product</a>
        </li> <br><br>
      </ul>

      <!-- user section -->
      <ul class="nav navbar-nav ms-auto">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.profile',uname=current_user.author)}}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Sign in</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {{ wtf.quick_form(comment_form) }}


</div>



{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {{ wtf.quick_form(pitch_entry) }}


</div>



{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
{% if user == current_user %}

{% endif %}
<br>
<br>
<div class="container">
  <div class="row">

    
    <!-- displaying  Username-->
    <div class="col-md-4">
      <h3>Author:  {{user.author| capitalize}} </h3>
      <br>
      <hr>
      <a href="{{url_for('main.update_profile',uname=user.author)}}">Edit profile</a>

      <!--Displaying user bio-->
      {% if user.bio %}
      <br>
      <h4>{{user.bio}}</h4>
      {%else%}
      <br>
      <p> {{user.author| capitalize}} has no bio </p>
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-8">
      {% if user.profile_pic_path %}

      <div class="card">
         <img class="card" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" height=50%>
      </div>
      <div class="row">
        {%else%}

        <h3><strong>No profile picture</strong></h3>

        {% endif %}

        {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.author)}}" method="post" enctype="multipart/form-data">
          <br>
          <input type="file"  name="photo" class="form-control" required>
          <br>
          <input type="submit">

        </form>
        {% endif %}
      </div>
    </div>
  </div>
  {% endblock %}